name: MLStudy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - alembic==1.17.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.3
      - cryptography==45.0.7
      - cycler==0.12.1
      - databricks-sdk==0.67.0
      - docker==7.1.0
      - dotenv==0.9.9
      - fastapi==0.119.0
      - fastmcp==2.1.2
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mcp==1.17.0
      - mdurl==0.1.2
      - mlflow==3.4.0
      - mlflow-skinny==3.4.0
      - mlflow-tracing==3.4.0
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - openapi-pydantic==0.5.1
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentry-sdk==2.41.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchvision==0.23.0
      - typer==0.19.2
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - waitress==3.0.2
      - wandb==0.22.2
      - websockets==15.0.1
      - werkzeug==3.1.3
